[package]
name = "compact-bar"
version = "1.0.0"
authors = ["Evgeny Mangasaryan", "tarkah <admin@tarkah.dev>"]
edition = "2021"
license = "MIT"

[dependencies]
ansi_term = "0.12"
regex = "1.10.6"
unicode-width = "0.1.8"
zellij-tile = "0.40"
zellij-tile-utils = "0.40"
